### ISSUE TITLE
nextion configuration

### ISSUE THREAD

**Issue by jschoch** [prototypicall/Didge#2]
Are you able to share the nextion editor configuration?

**Comment by prototypicall** [comment]
Terribly sorry for the delay. Life's been really busy lately.

I've attached the project file and the corresponding "tft firmware" file. It's just what I found on my disk. Please note that I do not recall which fonts, etc I've used and they may have license implications (possibly just atttribution and no fees). There are some shortcomings of the Nextion HMI in terms of dev. experience imho. I will be switching quite possibly to lvgl so consider the GUI part temporary.
[lather_v3.zip](https://github.com/prototypicall/Didge/files/5635093/lather_v3.zip)

**Comment by jschoch** [comment]
thanks!  No problem on the delay, life happens.    

I've hacked up (i'm terrible with c/c++) an esp32 ELS, I'm not doing any acceleration but it seems to work fine with a closed loop stepper.  Since it has wifi and I generally suck at UI and small screens I decided to poke around with websockets and react.  I think it is feasible to have most of the controls setup with the UI via wifi/html and have a simplified physical controller that is robust and chip proof.   Maybe I can just copy your nextion/lvgl setup and make it abstract so you could use your phone or a physical screen depending on preference.  I think i'm just going to keep a small oled and a very basic physical screen and do the rest with HTML/react/websockets.

I've flashed your code but the toolchain may be out of reach for the average arduino tinkerer.  This will help me run it finally. Anyway, happy to collaborate if you are interested in the web ui functionality or how some of the modes should work (like virtual stops) though I'm not sure what to do about the toolchain.

**Comment by prototypicall** [comment]
Thanks for the reply!

Your take on the ELS sounds really interesting. Regarding acceleration; Didge is a synchronous mechanism, i.e. locked to the "spindle". As long as the driving motor is able to keep up with the acceleration/deceleration of the spindle the acceleration is a non-issue. The scenario where I am talkin about is for instance, the spindle is rotating at high rpm and you have a button that changes the selected thread pitch from the finest to the coarsest (or vice versa). If you hit that button the synchronous system (Didge) would suddenly start sending this new much higher/lower frequency step pulses to the stepper driver and the motor would stall. So in some sense this is a corner case. But this case needs to be handled for the virtual stops anyway so it's definitely something I want to address.

For the UI part I definitely would like to have the control side wrapped up with an API (and a communication device options) to be easily integrated to any form factor or use case. Personally I feel like having some physical buttons for things like start and stop and for the virtual endstops, etc would be practical on a lathe. So one form factor I have in mind is a box like shape similar to ELS but have a D-pad for menu operations, a few buttons and a 2.8" touch screen.

I sure would like to collaborate. I am a c++ enthusiast but do not have any recent web development experience so would be good combined overlap.

I also have recent idea I want to try. By attaching another rotary encoder to the thread dial, I will dynamically calculate the actual position of the carriage and determine when the half-nut is engaged dis-engaged. This would make it even more easy to use without needing a DRO.

Let me know what you think.

**Comment by prototypicall** [comment]
Oh, and please let me know how the tool-chain part can be improved.

**Comment by jschoch** [comment]
Great!  Looking forward to collaborating.  

Regarding the physical inputs I've been playing with a smart input for the ELS, video here: https://youtu.be/Gye5O_PzPkk

You can also follow along here:  https://community.simplefoc.com/t/haptic-textures/301/4

Antun posted a very elegant way to do the virtual detents and it really really works well so ignore the oscillations in my video, that problem is fixed in a very robust way.

Let me know what you think.

Regarding the thread dial, i'm a bit confused and maybe you've not worked with a DRO or CNC lathe very much.  All you really need is a quick easy way to zero, set the virtual ELS DRO to a value, or home it to an absolute position.   Once it is set you must rely on the motor not missing steps but you need to rely on that in any case.  You should be able to easily translate the carriage position from steps into mm (or what ever units you want).  On a cheap mini lathe you likely will not want to be trying to disengage the half nuts when threading anyway since they can be somewhat difficult to precisely operate and if you miss your thread will be ruined.  If you motorize your X axis this can be automated and the half nuts never need to be disengaged during a single setup. Finally if you are off by one thread when you re-engage the half nut your controller will not know the thread dial doesn't help here and all your virtual DRO calculations would be off by the leadscrew pitch.  It may be simpler to have some sort of lockout that triggers when the half nut is disengaged but that would likely be better done with a switch.


Regarding the toolchain: i've been mainly using platform.io via Visual Studio Code and I've been using esp32 as the MCU.  I think platform.io can support the gnu arm c++ toolchain, the build I did of your code was using ubuntu though.  The react/websockets spike I did uses these libs.

```
#include "WiFi.h"
#include "ESPAsyncWebServer.h"
#include <ESPmDNS.h>
#include <ArduinoJson.h>
```

If you added wifi what would you use?

P.S.  I am self-taught with  most of my experience using elixir (functional).  My C and C++ skills are pretty bad but your code seems to be much closer to what I wish I could do in the arduino world which seems to ignore modern C++ and letting the compiler do work.  This is odd and frustrating for me and I hope to learn how to use modern C++ for embedded.

**Comment by prototypicall** [comment]
I've just had a chance to look at this and watch the video. The video looks already impressive and I am glad it's performing much better now.

Wow, there is so much similar thinking going on about haptic control and interface there. I am pleasantly surprised. The application I had in mind was to have them operate as virtual dials on the cross slide or for the carriage with small displays that can be zero-ed, or change units, etc. I will check out the thread for sure. It's also very useful to hear about the SimpleFOC project.

Regarding the thread dial, I should have done a better job at explaining. What you describe is the normal way virtual end stops would work. The carriage stays locked to the lead-screw through out the task (either threading or turning). Now if you had a DRO attached to the Z (i.e. tracking carriage position) and an ELS that supported it, you could make it work such that the operator can engage the half-nut at any time or position and resume the operation. This is possible because the ELS now knows the rotational position of the lead screw and also the position of the carriage. Now the twisty part is realizing that the thread dial is a device that can measure the relative position between the lead-screw and the carriage. First assume that the lead-screw is not rotating. In this situation it is similar to a rack in a rack and pinion actuator and the thread dial's business end is the pinion. So if we measure the rotation of the thread dial using a rotary encoder we can calculate position of the carriage in real-time (relative to the lead-screw but it's fixed for now). Now we can extend this to the case where the lead screw is rotating under the control of the ELS. We can now combine the rotational positions of both to calculate the real-time position of the carriage. So we don't need to keep the half-nut engaged all the time now :)

Assuming that the rotary encoder on a thread dial would be precise enough I think this would be very useful feature in keeping the wear low on the lead screw, especially when one needs to turn down a significant portion of a long stock. It may be a time saver as well as it will probably be quicker to crank the carriage back to start rather than the stepper doing it. It would also be a sort of a low cost Z only DRO. I am hoping to make this work before the end of the year when I will finally have some time off.

For the toolchain, thanks for the great feedback. I was intending to move to Visual Studio Code. It supports CMake with a plug-in so I may try to see if that would be a more easy set-up. I have tried PlatformIO in the past and did not care for it. I believe they are now using a paid subscription model? To be honest my hope was that with the GUI it most of the folks just would just need to flash a firmware with an ST-Link and configure their machines that way without delving into compiling so now I am hoping CMake and vscode would be a good enough solution.

And thanks for your patience.

Cheers.

**Comment by jschoch** [comment]
Thanks for explaining.  I was thinking the problem would be resolution but you only really need to know accuracy to around leadscrew pitch/4 and I see that  you could then use the Z stepper position to hone it in.  My thread dial for my 7x14 lathe has 16 teeth and the leadscrew is 2mm pitch so there is 32mm per revolution.   A 12bit encoder would give you a bit less than .01mm resolution.  The next question would be mounting but a magnetic encoder may work well.  My thread dial only uses a plain bearing and it is very small. 

Honestly though I don't think you'd need that function all that much.  I rarely turn anything longer than 60mm.  There is some line between going full CNC which brings me to another goal of mine.  I have my 7x14 setup with a centroid acorn cnc controller, but I absolutely hate the software.  I was considering making some switches so I could run it in ELS mode when I want to do semi-manual mode with a small MCU, or I can have the centroid controller run it when I use the full CNC mode (which is actually rare).  If grbl would implement spindle sync i'd sell the thing!

I'm going to start merging in my webUI code today.  Let me know if you have any ideas about abstracting it so it could be used by a stm32 through serial or i2c to something like a NRF24L01.  I was also looking at OSC SLIPSerial.

**Comment by jschoch** [comment]
i've made more progress.  I have synchronized jog to position (e.g. jog 2mm at .1mm pitch and stop) working but it was tricky and it is a bit of a hack.  I wonder if you've put any thought into how to implement this?  In my code I calculate the encoder's position in terms of stepper pulses, and then calculate the delta between a "tool pointer" and the current spindle position.  Since the spindle direction can change and reverse the feed direction, the logic is very confusing. I also think it is somewhat of a mistake to track things in terms of stepper pulses because if the pitch changes your encoder reference changes.  I found I had to reset the encoder to 0 when starting motion each time but that makes resyncing to a thread start break.  I'm refactoring today so I though i'd ask if you thought about it at all.

**Comment by prototypicall** [comment]
Again I am sorry for the delay in my response. I just had a chance to sync up on emails. I've been trying to get the garage (which was my "workshop" but we had to cram in office for my wife and I and everything on the shop side has been a mess) in semi working order. Anyway here's my 2 cents in case I am not too late.

I am a bit confused about the jog part. Is this for e.g. cutting a thread with virtual stops or for the jogging in terms of adjusting position for an operation? Assuming it is the former, my approach to how the virtual endstops work would is:

Assume we are in the middle of the operation (i.e actually cutting the thread) and we are moving the carriage in the correct speed (i.e. pitch) in sync with the spindle (using the method in Didge for example). We are approaching our endstop. When the carriage position matches the stop location we stop the carriage (with deceleration). Then the operator retracts, etc and "clicks" the start position command. Then we simply accelerate to the jog speed and move until we decelerate to stop at the start position. Then the operator adjust the cross feed, etc then hits the "feed" button. We then need to accelerate to the same the target speed (determined by the spindle speed) and then engage the synchronized motion part. Of course we need to be at the right position, too. For that we need to keep track of the spindle position and have a simple path planning to make sure that we start the acceleration at the right time so that when the carriage hits the target speed it would be at the correct position. For this to work we need the spindle to be at the same speed. Solving this for the general case would be much more involved.

Hope this makes sense. Let me know how it's going. I am hoping to get back to the my project after I am done with the garage and hopefully get my MSLA printer, mini mill and lathe functional so that I can finally get the project done. 

I am very intrigued about the haptic feedback control mechanisms but for the sake of getting this project into a release-able state I will have to get away with just an encoder and some buttons for now. But I have bought a similar (or even possibly the same) brushless motor and looking forward to collaborate on that.

Cheers.

**Comment by jschoch** [comment]
sorry if I wasn't clear.  My first attempt calculated a delta based on the current encoder's position translated into stepper steps.  It used the delta > 0 or delta < 0 to decide if it should generate a step or not.  Once it stepped the delta would be 0 and it would do nothing.  it is all jambed in this `if (pos_feeding)` area  https://github.com/jschoch/ESPels/blob/master/src/src/Stepper.cpp#L234-L338  

That version works because I reset the encoder to zero before I start moving.  What didn't work was [here](https://github.com/jschoch/ESPels/blob/master/src/src/web.cpp#L177]) was trying calculate the encoder position in steps based on the where the tool should be.  It worked ok for Z+, it would work ok for a Z- only when starting from encoder position 0!  A Z- move starting from encoder position -6400 would calculate the delta wrong and it would try to do the full move without any ticks from the encoder.  This also brings up the difficulty of changing the pitch mid operation, which I'm not clear how best to do to.

I've now finally spent some "quality" time with your code, I avoided this previously because of my lack of c++ experience and the difficulties of getting boost to work with PlatformIO or the Arduino IDE.  Turns out I can run the jump functions without Rational.h  A couple things threw me, the main one was the way you deal with the step pausing after changing the delay signal by flipping the dir signal, and then I also didn't realized you were filtering your encoder signals... I think I have a better grasp on how it works now, though a fundamental understanding of the the bresenham derivative still escapes me. 

I have a modified version of your gear code running.  In my setup I've moved to using the esp32's RMT peripheral to generate the step signals.  It can do 100khz steps, maybe even 200khz!   I'd like to use smaller micro steps but if i use 32 microsteps the gear code will only do .7mm pitch with my encoder and lead screw.   I'd love to workout slopes > 1.  I found a decent explanation of how to split up the slope of the line into 8 quadrants and then decide how to make a transformation that still works https://www.instructables.com/CNC-Drum-Plotter/

I'm just going to reduce my micro stepping for now to try to get your code working with my existing logic.  I do want to try to modify it so it can do slopes > 1.  Let me know if there is any issue with my approach.

So, to wrap up, I'm refactoring to use your gear code, trying to understand how to safely change pitches mid operation, and wanting to do lines with slop > 1.  I havn't jumped back into working on the haptic controller yet but the next thing to do there is build an enclosure and to decide on a protocol for sending the signals.   Have you looked at SLIP yet?

https://en.wikipedia.org/wiki/Serial_Line_Internet_Protocol

The other idea floating around is to use msgpack since i'm already using it for the webUI.  I have no idea what the messages should look like though, maybe something like

```json
"event": {
 "device id": 1,
 "etype": BTN,
 "e": BTN_UP
}

or...

"event": {
 "device id": 2,
 "etype": ENC,
 "e": ENC_UP
}
```

**Comment by prototypicall** [comment]
Sorry about the curveballs in the code. It's great that you got it working. Step pausing you mention is due to the requirements of stepper drivers regarding direction change. Normally we can send step pulses one after the other but when there is a direction change the direction signal needs to be recognized before a step pulse is sent. This is specified for each stepper driver as hold time. In order to reduce the latency for the average case (where the spindle is rotating at the same speed and there is no direction change) the code configures the timer to just generate the step pulse. When there is a direction change we temporarily configure the timer to delay the step pulse to satisfy the hold time. Due to the constraints for the STM32F1 timers we need to manually do some operations for that.

> I'd like to use smaller micro steps but if i use 32 microsteps the gear code will only do .7mm pitch with my encoder and lead screw. I'd love to workout slopes > 1. I found a decent explanation of how to split up the slope of the line into 8 quadrants and then decide how to make a transformation that still works https://www.instructables.com/CNC-Drum-Plotter/

What is motivating you to use smaller micro stepping? Since the accuracy is significantly reduced as you go smaller the rationale for the FDM printers, which are low precision compared to metal lathes or mills, is to reduce vibrations and noise. Once very popular Gecko drives are configured for 10 micro steps for example. If it is indeed for reducing vibarations/smoother operation, recent digital stepper drivers are faking sinusiodial interpolation to achieve pretty good results without losing accuracy, ditto closed loop stepper systems. At any rate my suggestion would be to use a timing belt to attach the optical encoder and use a smaller pulley for the encoder side to basically increase it's resolution as you wish. Since there is no load it should be possible to achieve a 1:4 ratio so a 1000 pulse encoder would be like a 4000 pulse one. You can even choose arbitrary gear ratios (e.g. if you want to use existing pulleys) and the code will work if you specify the gear ratio in the config.

The approach for the plotter would not work because unlike the plotter case we rely on the spindle pulses to decide if the generate a step or not (ignore the smoothing for now). The plotter trick works because one can change the "master" axis to be X or Y but in our case that would imply that we could read the motor and adjust the spindle position wrt that.

It is however possible to make an interpolating step generator that would generate intermediate step pulses since we know the spindle speed in real time. I will consider implementing this. But hopefully the above discussion would help in the mean time.

> So, to wrap up, I'm refactoring to use your gear code, trying to understand how to safely change pitches mid operation, and wanting to do lines with slop > 1. I havn't jumped back into working on the haptic controller yet but the next thing to do there is build an enclosure and to decide on a protocol for sending the signals. Have you looked at SLIP yet?

For the gear change part I think the easiest way would be to disallow gear changes while the spindle is rotating (similar to the actual gearbox). In terms of the synchronized motion in the firmware you can just clear the error and update the pulse ratio and it should work. This should work for feed adjustment without any issues but it would not work for the threads as easily only because the new speed and the old speed could be too different for the stepper to jump instantly (jerk). Then there needs to be ramping up or down to match the speed and then engage the algorithm :)

The first thing I will be doing after getting the garage done is the enclosure as well. I've seen your video about the tablet UI and looks pretty nifty for sure. I will be going for a small 3d printed enclosure to put the nextion display (which I dislike very much now) and an encoder and some buttons to match the size of the plastic electrical box of the lathe. I need to get the project complete and get it out hopefully soon.

Merry Christmas!

**Comment by jschoch** [comment]
Thanks for the response, Merry Chirstmas!

The web UI still needs lots of work but it is pretty easy to add features to and I have a bunch of status updates that get sent over.  Msgpack is much faster on the esp32 and I've switched to that from raw json.  I've put almost zero effort into the layout and UI design so there is much more that can be done.  I made a mild steel part christmas eve with the slave position jogging and it was very easy to do.

The way the esp32 RMT timer works is that you have blocks of bits that you can configure to send pulses.  I just use 2 blocks and the step gets created , no need to wait and then turn the signal low.  This changes the logic for the dir change pause a bit.

https://github.com/jschoch/ESPels/blob/timer_refactor/src/src/motion.cpp#L43

and 

https://github.com/jschoch/ESPels/blob/timer_refactor/src/src/rmtStepper.h#L48

While i like the stm32, the ease of updating the webUI and the fact that I can run it on my phone, laptop, or a tablet is way easier to work with than updating display code.  I have a 4th axis that I want to be able to use on my manual milling machine as well as my CNC and I'm going to generalize the RMT stepping into a library that I can use with the websockets code to control it like a digital indexing head.  Learing this ELS stuff will make doing that a breeze!
